UI/Controllers/ApplicantResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloud.EntityFrameworkDataAccess;
using CareerCloud.Pocos;

namespace UI.Controllers
{
    public class ApplicantResumeController : Controller
    {
        private readonly CareerCloudContext _context;

        public ApplicantResumeController(CareerCloudContext context)
        {
            _context = context;
        }

        // GET: ApplicantResume
        public async Task<IActionResult> Index(Guid? Id)
        {
            var careerCloudContext = _context.ApplicantResumes.Where(a => a.Applicant == Id);
            //.Include(a => a.ApplicantProfile);
            return View(await careerCloudContext.ToListAsync());
        }

        // GET: ApplicantResume/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantResumePoco = await _context.ApplicantResumes
                .Include(a => a.ApplicantProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantResumePoco == null)
            {
                return NotFound();
            }

            return View(applicantResumePoco);
        }

        // GET: ApplicantResume/Create
        public IActionResult Create()
        {
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id");
            return View();
        }

        // POST: ApplicantResume/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Applicant,Resume,LastUpdated")] ApplicantResumePoco applicantResumePoco)
        {
            if (ModelState.IsValid)
            {
                applicantResumePoco.Id = Guid.NewGuid();
                _context.Add(applicantResumePoco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantResumePoco.Applicant);
            return View(applicantResumePoco);
        }

        // GET: ApplicantResume/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantResumePoco = await _context.ApplicantResumes.FindAsync(id);
            if (applicantResumePoco == null)
            {
                return NotFound();
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantResumePoco.Applicant);
            return View(applicantResumePoco);
        }

        // POST: ApplicantResume/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Applicant,Resume,LastUpdated")] ApplicantResumePoco applicantResumePoco)
        {
            if (id != applicantResumePoco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicantResumePoco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicantResumePocoExists(applicantResumePoco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantResumePoco.Applicant);
            return View(applicantResumePoco);
        }

        // GET: ApplicantResume/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantResumePoco = await _context.ApplicantResumes
                .Include(a => a.ApplicantProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantResumePoco == null)
            {
                return NotFound();
            }

            return View(applicantResumePoco);
        }

        // POST: ApplicantResume/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var applicantResumePoco = await _context.ApplicantResumes.FindAsync(id);
            _context.ApplicantResumes.Remove(applicantResumePoco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicantResumePocoExists(Guid id)
        {
            return _context.ApplicantResumes.Any(e => e.Id == id);
        }
    }
}

UI/Controllers/ApplicantSkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloud.EntityFrameworkDataAccess;
using CareerCloud.Pocos;

namespace UI.Controllers
{
    public class ApplicantSkillController : Controller
    {
        private readonly CareerCloudContext _context;

        public ApplicantSkillController(CareerCloudContext context)
        {
            _context = context;
        }

        // GET: ApplicantSkill
        public async Task<IActionResult> Index(Guid? Id)
        {
            var careerCloudContext = _context.ApplicantSkills.Where(a => a.Applicant == Id);
            //.Include(a => a.ApplicantProfile);
            return View(await careerCloudContext.ToListAsync());
        }

        // GET: ApplicantSkill/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantSkillPoco = await _context.ApplicantSkills
                .Include(a => a.ApplicantProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantSkillPoco == null)
            {
                return NotFound();
            }

            return View(applicantSkillPoco);
        }

        // GET: ApplicantSkill/Create
        public IActionResult Create()
        {
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id");
            return View();
        }

        // POST: ApplicantSkill/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Applicant,Skill,SkillLevel,StartMonth,StartYear,EndMonth,EndYear")] ApplicantSkillPoco applicantSkillPoco)
        {
            if (ModelState.IsValid)
            {
                applicantSkillPoco.Id = Guid.NewGuid();
                _context.Add(applicantSkillPoco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantSkillPoco.Applicant);
            return View(applicantSkillPoco);
        }

        // GET: ApplicantSkill/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantSkillPoco = await _context.ApplicantSkills.FindAsync(id);
            if (applicantSkillPoco == null)
            {
                return NotFound();
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantSkillPoco.Applicant);
            return View(applicantSkillPoco);
        }

        // POST: ApplicantSkill/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Applicant,Skill,SkillLevel,StartMonth,StartYear,EndMonth,EndYear")] ApplicantSkillPoco applicantSkillPoco)
        {
            if (id != applicantSkillPoco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicantSkillPoco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicantSkillPocoExists(applicantSkillPoco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantSkillPoco.Applicant);
            return View(applicantSkillPoco);
        }

        // GET: ApplicantSkill/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantSkillPoco = await _context.ApplicantSkills
                .Include(a => a.ApplicantProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantSkillPoco == null)
            {
                return NotFound();
            }

            return View(applicantSkillPoco);
        }

        // POST: ApplicantSkill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var applicantSkillPoco = await _context.ApplicantSkills.FindAsync(id);
            _context.ApplicantSkills.Remove(applicantSkillPoco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicantSkillPocoExists(Guid id)
        {
            return _context.ApplicantSkills.Any(e => e.Id == id);
        }
    }
}

UI/Controllers/ApplicantWorkHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloud.EntityFrameworkDataAccess;
using CareerCloud.Pocos;

namespace UI.Controllers
{
    public class ApplicantWorkHistoryController : Controller
    {
        private readonly CareerCloudContext _context;

        public ApplicantWorkHistoryController(CareerCloudContext context)
        {
            _context = context;
        }

        // GET: ApplicantWorkHistory
        public async Task<IActionResult> Index(Guid? Id)
        {
            var careerCloudContext = _context.ApplicantWorkHistorys.Where(a => a.Applicant == Id);
                //.Include(a => a.ApplicantProfile).Include(a => a.SystemCountryCode);
            return View(await careerCloudContext.ToListAsync());
        }

        // GET: ApplicantWorkHistory/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantWorkHistoryPoco = await _context.ApplicantWorkHistorys
                .Include(a => a.ApplicantProfile)
                .Include(a => a.SystemCountryCode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantWorkHistoryPoco == null)
            {
                return NotFound();
            }

            return View(applicantWorkHistoryPoco);
        }

        // GET: ApplicantWorkHistory/Create
        public IActionResult Create()
        {
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id");
            ViewData["CountryCode"] = new SelectList(_context.SystemCountryCodes, "Code", "Code");
            return View();
        }

        // POST: ApplicantWorkHistory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Applicant,CompanyName,CountryCode,Location,JobTitle,JobDescription,StartMonth,StartYear,EndMonth,EndYear")] ApplicantWorkHistoryPoco applicantWorkHistoryPoco)
        {
            if (ModelState.IsValid)
            {
                applicantWorkHistoryPoco.Id = Guid.NewGuid();
                _context.Add(applicantWorkHistoryPoco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantWorkHistoryPoco.Applicant);
            ViewData["CountryCode"] = new SelectList(_context.SystemCountryCodes, "Code", "Code", applicantWorkHistoryPoco.CountryCode);
            return View(applicantWorkHistoryPoco);
        }

        // GET: ApplicantWorkHistory/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantWorkHistoryPoco = await _context.ApplicantWorkHistorys.FindAsync(id);
            if (applicantWorkHistoryPoco == null)
            {
                return NotFound();
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantWorkHistoryPoco.Applicant);
            ViewData["CountryCode"] = new SelectList(_context.SystemCountryCodes, "Code", "Code", applicantWorkHistoryPoco.CountryCode);
            return View(applicantWorkHistoryPoco);
        }

        // POST: ApplicantWorkHistory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Applicant,CompanyName,CountryCode,Location,JobTitle,JobDescription,StartMonth,StartYear,EndMonth,EndYear")] ApplicantWorkHistoryPoco applicantWorkHistoryPoco)
        {
            if (id != applicantWorkHistoryPoco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicantWorkHistoryPoco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicantWorkHistoryPocoExists(applicantWorkHistoryPoco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Applicant"] = new SelectList(_context.ApplicantProfiles, "Id", "Id", applicantWorkHistoryPoco.Applicant);
            ViewData["CountryCode"] = new SelectList(_context.SystemCountryCodes, "Code", "Code", applicantWorkHistoryPoco.CountryCode);
            return View(applicantWorkHistoryPoco);
        }

        // GET: ApplicantWorkHistory/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicantWorkHistoryPoco = await _context.ApplicantWorkHistorys
                .Include(a => a.ApplicantProfile)
                .Include(a => a.SystemCountryCode)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantWorkHistoryPoco == null)
            {
                return NotFound();
            }

            return View(applicantWorkHistoryPoco);
        }

        // POST: ApplicantWorkHistory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var applicantWorkHistoryPoco = await _context.ApplicantWorkHistorys.FindAsync(id);
            _context.ApplicantWorkHistorys.Remove(applicantWorkHistoryPoco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicantWorkHistoryPocoExists(Guid id)
        {
            return _context.ApplicantWorkHistorys.Any(e => e.Id == id);
        }
    }
}

UI/Views/_ApplicantEducation.cshtml
@model IEnumerable<CareerCloud.Pocos.ApplicantEducationPoco>
@{
    ViewData["Title"] = "ApplicantEducation";
}

<h1>ApplicantEducation</h1>

<p>
    <a asp-controller="ApplicantEducation" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Major)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CertificateDiploma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletionPercent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicantProfilePoco)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Major)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CertificateDiploma)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletionPercent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeStamp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicantProfilePoco.Id)
                </td>
                <td>
                    <a asp-controller="ApplicantEducation" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="ApplicantEducation" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="ApplicantEducation" asp-action="Delete" asp-route-id="@item.Id">Delete</a> 

                </td>
            </tr>
        }
    </tbody>
</table>

UI/Views/_ApplicantJobApplication.cshtml
@model IEnumerable<CareerCloud.Pocos.ApplicantJobApplicationPoco>

@{
    ViewData["Title"] = "ApplicantJobApplication";
}

@{ if (Model != null)
    {
        <h1>ApplicantJobApplication</h1>
        <p>
            <a asp-controller="ApplicantJobApplication" asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ApplicationDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ApplicantProfilePoco)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CompanyJob)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ApplicationDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ApplicantProfilePoco.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompanyJob.Id)
                        </td>
                        <td>
                            <a asp-controller="ApplicantJobApplication" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-controller="ApplicantJobApplication" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-controller="ApplicantJobApplication" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

UI/Views/_ApplicantResumes.cshtml
@model IEnumerable<CareerCloud.Pocos.ApplicantResumePoco>

@{
    ViewData["Title"] = "Applicant Resume";
}

<h1>Applicant Resume</h1>

<p>
    <a  asp-controller="ApplicantResume"  asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Resume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastUpdated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicantProfile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Resume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastUpdated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicantProfile.Id)
            </td>
            <td>
                <a asp-controller="ApplicantResume" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="ApplicantResume" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-controller="ApplicantResume" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

            </td>
        </tr>
}
    </tbody>
</table>

UI/Views/_ApplicantSkills.cshtml
@model IEnumerable<CareerCloud.Pocos.ApplicantSkillPoco>

@{
    ViewData["Title"] = "Applicant Skill";
}

<h1>Applicant Skill</h1>

<p>
    <a asp-controller="ApplicantSkill" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Skill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SkillLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicantProfile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Skill)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SkillLevel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartMonth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndMonth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicantProfile.Id)
                </td>
                <td>
                    <a asp-controller="ApplicantSkill" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="ApplicantSkill" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="ApplicantSkill" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

UI/Views/_ApplicantWorkHistory.cshtml
@model IEnumerable<CareerCloud.Pocos.ApplicantWorkHistoryPoco>

@{
    ViewData["Title"] = "Applicant WorkHistory";
}

<h1>Applicant WorkHistory</h1>

<p>
    <a asp-controller="ApplicantWorkHistory" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicantProfile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SystemCountryCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartMonth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndMonth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicantProfile.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SystemCountryCode.Code)
                </td>
                <td>
                    <a asp-controller="ApplicantWorkHistory" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="ApplicantWorkHistory" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="ApplicantWorkHistory" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

UI/Views/_CompanyDescription.cshtml
@model IEnumerable<CareerCloud.Pocos.CompanyDescriptionPoco>

@{
    ViewData["Title"] = "Company Description";
}

<h1>Company Description</h1>

<p>
    <a asp-controller="CompanyDescription" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyProfile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SystemLanguageCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyProfile.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SystemLanguageCode.LanguageID)
                </td>
                <td>
                    <a asp-controller="CompanyDescription" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="CompanyDescription" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="CompanyDescription" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>